import { GameMap } from "../arrows.js";

const top = new GameMap("AAAJAAAAAAAGCREQACAAMAABAAICAwIEAgUEBgQHAwgBCQEKAQsBDAENAQ4BDwEMAUEBMgIKDSICIwIkAiUCJgInAigCKQIqAisCLAItAi4CLwITAEIBAQAzAxAAQwEOATQBRAQBAAAAAQkPAAEBAQIBAwEEAQUBBgEHAQgBCQEKAQsBDAENAQ4BDwEKDyACIQIiAiMCJAIlAiYCJwIoAikCKgIrAiwCLQIuAi8CAgAAAAEJDwABAQECAQMBBAEFBAYDBwEIAQkBCgELAQwBDQEOAQ8BCg8gAiECIgIjAiQCJQImAicCKAIpAioCKwIsAi0CLgIvAgMAAAABCQ8AAQEBAgEDAQQBBQEGAQcBCAEJAQoBCwEMAQ0BDgEPAQoPIAIhAiICIwIkAiUCJgInAigCKQIqAisCLAItAi4CLwIEAAAAAQkPAAEBAQIEAwMEAQUBBgEHAQgECQMKAQsBDAENAQ4BDwEKDyACIQIiAiMCJAIlAiYCJwIoAikCKgIrAiwCLQIuAi8CBQAAAAEJDwABAQECAQMBBAEFAQYBBwEIAQkBCgELAQwBDQEOAQ8BCg8gAiECIgIjAiQCJQImAicCKAIpAioCKwIsAi0CLgIvAgYAAAABCQ8AAQEBAgEDAQQBBQEGAQcBCAEJAQoBCwEMAQ0BDgEPAQoPIAIhAiICIwIkAiUCJgInAigCKQIqAisCLAItAi4CLwIHAAAAAQkPAAEBAQIBAwEEAQUEBgQHAwgBCQEKAQsBDAENAQ4BDwEKDyACIQIiAiMCJAIlAiYCJwIoAikCKgIrAiwCLQIuAi8CCAAAAAEJCAABAQECAQMBBAEFABYAJgA2AAoEIAIhAiICIwIkAg==");
const bottom = new GameMap("AAAJAAAAAAAJChRgA2IDZAMmAUYCVgBmA3YAFwInAQgDKAEZAykBGgMbARwDLAEdAR4DHwEMBwQCFAIkAAcARwFJAysBLwEOATQBRQQYFKQBtAHEAZUBpQG1AcUB1QGWAKYAtgDGANYAlwOnA7cDxwPXA6gDuAPIAwYABgIEABYCCwM2ADcCGAMqAAEIhgAJAgoDCwMMAw0DLQUOAw8DCQZIAEoASwFMA00DTgNPAxIALgUBAAAABgEPAAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMKDRADEQETARQDFQEWAxcBGAMZARoDGwEcAx0BHgMDASABHwIJD0ADQQNCA0MDRANFA0YDRwNIA0kBSgFLAUwBTQFOAU8BCwAhAA0AEgcEDSIBIwEkASUBJgEnASgBKQEqASsBLAEtAS4BLwECAAAABAEPAAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMKBxADKAEqASsDLAEtAy4BLwMEDyABEQMhARIDIgETAyMBFAMkARUDJQEWAyYBFwMnARgDCQ9AAUEBQgFDAUQBRQFGAUcBSAFJBEoDSwFMAU0BTgFPAQsAKQMDAAAAAgEPAAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMKDyABIQMiASMDJAElAyYBJwMoASkDKgErAywBLQMuAS8DCQ9AAUEBQgFDAUQBRQFGAUcBSAFJAUoBSwFMAU0BTgFPAQQAAAACAQ8AAwEDAgMDAwQDBQMGAwcDCAMJAwoDCwMMAw0DDgMPAwoPIAEhAyIBIwMkASUDJgEnAygBKQMqASsDLAEtAy4BLwMJD0ABQQFCAUMBRAFFAUYBRwFIAUkBSgFLAUwBTQFOAU8BBQAAAAIBDwADAQMCAwMDBAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DCg8gASEDIgEjAyQBJQMmAScDKAEpAyoBKwMsAS0DLgEvAwkPQAFBAUIBQwFEAUUBRgFHAUgBSQFKAUsBTAFNAU4BTwEGAAAABAEPAAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNAw4DDwMKBSABIQMiASMDJAElAwkPQANBA0IDQwNEA0UDRgNHA0gDSQNKA0sDTANNA04DTwMLABYCBBImARcDJwEYAygBGQMpARoDKgEbAysBHAMsAR0DLQEeAy4BHwMvAQcAAAACAQ8AAwEDAgMDAwQDBQMGAwcDCAMJAwoDCwMMAw0DDgMPAwQfEAMgAREDIQESAyIBEwMjARQDJAEVAyUBFgMmARcDJwEYAygBGQMpARoDKgEbAysBHAMsAR0DLQEeAy4BHwMvAQkPQANBA0IDQwNEA0UDRgNHA0gDSQNKA0sDTANNA04DTwMIAAAABAEHAAMBAwIDAwMEAwUDBgMHAwQLEAMgAREDIQESAyIBEwMjARQDJAEVAxYDCQlAA0EDQgNDA0QDRQM2AycDGAMJAwsAJQARAAgD");
const line = new GameMap("AAAJAAAAAAAGCQEAABAABgACABMAEgEMAAMAEAATAQoLBAMFAgYCBwIIAgkCCgILAgwCDQIOAg8CBwAUAQEAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgIAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgMAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgQAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgUAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgYAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAgcAAAAACg8AAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMAg0CDgIPAggAAAABCgQAAgECAgIDAgQCCQEGABYA");

export const builderConfig = {
    top,
    bottom,
    line,
    header: (length) => [length & 0xFF, length >> 8], // the program length, low byte first
    rowBytes: 32, // data bytes on one row of the diskette
    minBytes: 64, // the smallest payload a diskette can carry: two rows
    rowPitch: 2,  // map rows taken by one data row
    dataX: 9,     // x of the first data arrow in a row
    cellPitch: 1, // x step between the cells of one byte
    cells: [      // the arrow for each two-bit value of a cell
        { type: 1, rotation: 1, flipped: false },
        { type: 7, rotation: 1, flipped: false },
        { type: 7, rotation: 1, flipped: true },
        { type: 8, rotation: 1, flipped: false }
    ],
    topX: 4,      // x the top cap is pasted at
    lineX: 4,     // x the row separator is pasted at
    lineDy: 1,    // separator y relative to its row: the one below it
    bottomDy: 2,  // bottom cap y = row count * rowPitch + bottomDy: every row is standard,
                  // so the cap starts right under the last one
};
