import { GameMap } from "../arrows.js";

const top = new GameMap("AAACAAAAAAAGCRMAARAAIAAwAEAAAQICAgMCBAIFBAYEBwMIAQkBCgELAQwBDQEOAQ8BDAFBATICEwBCAQEAMwMQAEMBDgE0AUQEChUlAkUCJgJGAicCRwIoAkgCKQJJAioCSgIrAksCLAJMAi0CTQIuAk4CLwJPAgEAAAABCQoAAQEBAgEDAQQBBQEGARYAJgA2AEYACgkgAkACIQJBAiICQgIjAkMCJAJEAg==");
const bottom = new GameMap("AAAEAAAAAQABCggAAwIDEwAEAwYDCAMKAwwDDgMYCCMAMwBDACQDNANEAyUDNQNFAwAAAAAOCRsBABEAIQAxAEEAUQBhAXEBgQGRAaEAsQDBANEA4QDiAOQE5QTmBOcE6ATpBOoE6wTsBO0E7gTvBA4GAwbGA1cEyAPKA8wDzgMKFhMAUwRjAcMA8wAkAAUDFQZlASYDRgCmA2cBaAKIArgDWQNaAboDWwOsA74DXwMLCTMAFAElAQYHZgF2AocAeAFJA2kBDAtzAJMA0wAEAFQClAGWBZgFmgWcBZ4FfwEDBYMAZAK0AHUBqAJcAhIBowBEAgE5swA0AqQAVQGFATYBVgKGAbYABwMXAScAdwMIAxgBKAM4AQkDGQApAzkBiQEKBhoBKgM6AUoDigELAxsBKwM7AEsDiwEMAxwCLAI8AkwDjAENAx0ALQA9AU0AjQEOAh4BLgM+AE4DjgEPAx8CLwE/Ak8DjwENAnQGWAFdBxMIxAC1BjcCtwZIArkGuwa9Br8GBwE1AkUCEAyVBMUDRwGXBMcHmQTJB5sEywedBM0HnwTPBwUFpQSnBKkEqwStBK8EBAp6AaoCawF7AGwBfAO8AG0BfQNuAq4CBgB+AQEAAAALASYAAxABMANAAIABAQMRADEBQQOBAQICEgEiAzIBQgNyA4IBAwMTASMDMwJDA1MBYwCDAQQDFAEkAzQARABUAGQDBQMVAiUCNQJFAlUCZQMLAyABIQOEAfUCEAZQA3AAkQTBB2IAkwTDBwwDYAGQBVIHkgUKBqADsgN0A5UCtQLVAnYDBAGwAKICDgLAA8IDtAcJFOAE4QTiBOMA5ADmAAcAFwAnADcARwBXAGcAdwCHAJcApwC3AMcA1wDnABMEUQNhAXEDsQazBgUBoQSjBAgAlAENAKQHAQABAAAKAgADAgMEAw==");
const line = new GameMap("AAACAAAAAAAGCQEAABAAEwACAQYAEgAQAAMBDAATAAcABAEKCxQDFQIWAhcCGAIZAhoCGwIcAh0CHgIfAgEAAAABCgQQAhECEgITAhQCCQEGABYA");

export const builderConfig = {
    top,
    bottom,
    line,
    rowBytes: 4, // data bytes on one row of the diskette
    minBytes: 8, // the smallest payload a diskette can carry
    dataX: 6,    // x of the first data arrow in a row
    topX: 1,     // x the top cap is pasted at
    lineX: 1,    // x the row separator is pasted at
    lineDy: 0,   // separator y relative to its row
    bottomDy: 2, // bottom cap y = row count * 2 + bottomDy
};
