export const Args = {
    A: 0x0,
    B: 0x1,
    C: 0x2,
    D: 0x3,
    BYTE: 0x4
};

export const argTypeNames = ["a", "b", "c", "d", "addr"];

export const instructions = [
    "adc", "add", "and", "clr", "dec", "hlt", "inc", "jc",
    "jmp", "jnc", "jno", "jns", "jnz", "jo", "js", "jz",
    "ld", "ldi", "mov", "neg", "nop", "not", "or", "rcl",
    "rcr", "rnd", "sar", "sbb", "shl", "shr", "st", "sub",
    "test", "xor"
];

export const registers = ["a", "b", "c", "d"];

export const keywords = ["db", "equ"];

class Command {
    constructor(instruction, args, opcode) {
        this.instruction = instruction;
        this.args = args;
        this.opcode = opcode;
    }

    match(instruction, args) {
        const argc = this.args.length;
        let match = this.instruction === instruction && argc === args.length;
        if (match)
            for (let i = 0; i < argc; ++i) {
                const argType = this.args[i];
                const { type } = args[i];
                if (argType !== type) {
                    match = false;
                    break;
                }
            }
        return match;
    }
}

export const commands = [
    new Command("nop", [], 0x00),
    new Command("hlt", [], 0x01),
    new Command("jmp", [Args.BYTE], 0x03),
    new Command("jmp", [Args.A], 0x04),
    new Command("jmp", [Args.B], 0x05),
    new Command("jmp", [Args.C], 0x06),
    new Command("jmp", [Args.D], 0x07),
    new Command("jz", [Args.BYTE], 0x08),
    new Command("js", [Args.BYTE], 0x09),
    new Command("jc", [Args.BYTE], 0x0A),
    new Command("jo", [Args.BYTE], 0x0B),
    new Command("jnz", [Args.BYTE], 0x0C),
    new Command("jns", [Args.BYTE], 0x0D),
    new Command("jnc", [Args.BYTE], 0x0E),
    new Command("jno", [Args.BYTE], 0x0F),

    new Command("jz", [Args.A], 0x10),
    new Command("js", [Args.A], 0x11),
    new Command("jc", [Args.A], 0x12),
    new Command("jo", [Args.A], 0x13),
    new Command("jz", [Args.B], 0x14),
    new Command("js", [Args.B], 0x15),
    new Command("jc", [Args.B], 0x16),
    new Command("jo", [Args.B], 0x17),
    new Command("jz", [Args.C], 0x18),
    new Command("js", [Args.C], 0x19),
    new Command("jc", [Args.C], 0x1A),
    new Command("jo", [Args.C], 0x1B),
    new Command("jz", [Args.D], 0x1C),
    new Command("js", [Args.D], 0x1D),
    new Command("jc", [Args.D], 0x1E),
    new Command("jo", [Args.D], 0x1F),

    new Command("jnz", [Args.A], 0x20),
    new Command("jns", [Args.A], 0x21),
    new Command("jnc", [Args.A], 0x22),
    new Command("jno", [Args.A], 0x23),
    new Command("jnz", [Args.B], 0x24),
    new Command("jns", [Args.B], 0x25),
    new Command("jnc", [Args.B], 0x26),
    new Command("jno", [Args.B], 0x27),
    new Command("jnz", [Args.C], 0x28),
    new Command("jns", [Args.C], 0x29),
    new Command("jnc", [Args.C], 0x2A),
    new Command("jno", [Args.C], 0x2B),
    new Command("jnz", [Args.D], 0x2C),
    new Command("jns", [Args.D], 0x2D),
    new Command("jnc", [Args.D], 0x2E),
    new Command("jno", [Args.D], 0x2F),

    new Command("st", [Args.A, Args.BYTE], 0x30),
    new Command("st", [Args.B, Args.A], 0x31),
    new Command("st", [Args.C, Args.A], 0x32),
    new Command("st", [Args.D, Args.A], 0x33),
    new Command("st", [Args.A, Args.B], 0x34),
    new Command("st", [Args.B, Args.BYTE], 0x35),
    new Command("st", [Args.C, Args.B], 0x36),
    new Command("st", [Args.D, Args.B], 0x37),
    new Command("st", [Args.A, Args.C], 0x38),
    new Command("st", [Args.B, Args.C], 0x39),
    new Command("st", [Args.C, Args.BYTE], 0x3A),
    new Command("st", [Args.D, Args.C], 0x3B),
    new Command("st", [Args.A, Args.D], 0x3C),
    new Command("st", [Args.B, Args.D], 0x3D),
    new Command("st", [Args.C, Args.D], 0x3E),
    new Command("st", [Args.D, Args.BYTE], 0x3F),

    new Command("ld", [Args.A, Args.A], 0x40),
    new Command("ld", [Args.B, Args.A], 0x41),
    new Command("ld", [Args.C, Args.A], 0x42),
    new Command("ld", [Args.D, Args.A], 0x43),
    new Command("ld", [Args.A, Args.B], 0x44),
    new Command("ld", [Args.B, Args.B], 0x45),
    new Command("ld", [Args.C, Args.B], 0x46),
    new Command("ld", [Args.D, Args.B], 0x47),
    new Command("ld", [Args.A, Args.C], 0x48),
    new Command("ld", [Args.B, Args.C], 0x49),
    new Command("ld", [Args.C, Args.C], 0x4A),
    new Command("ld", [Args.D, Args.C], 0x4B),
    new Command("ld", [Args.A, Args.D], 0x4C),
    new Command("ld", [Args.B, Args.D], 0x4D),
    new Command("ld", [Args.C, Args.D], 0x4E),
    new Command("ld", [Args.D, Args.D], 0x4F),

    new Command("ld", [Args.A, Args.BYTE], 0x50),
    new Command("ld", [Args.B, Args.BYTE], 0x51),
    new Command("ld", [Args.C, Args.BYTE], 0x52),
    new Command("ld", [Args.D, Args.BYTE], 0x53),
    new Command("ldi", [Args.A, Args.BYTE], 0x54),
    new Command("ldi", [Args.B, Args.BYTE], 0x55),
    new Command("ldi", [Args.C, Args.BYTE], 0x56),
    new Command("ldi", [Args.D, Args.BYTE], 0x57),

    new Command("inc", [Args.A], 0x60),
    new Command("add", [Args.B, Args.A], 0x61),
    new Command("add", [Args.C, Args.A], 0x62),
    new Command("add", [Args.D, Args.A], 0x63),
    new Command("add", [Args.A, Args.B], 0x64),
    new Command("inc", [Args.B], 0x65),
    new Command("add", [Args.C, Args.B], 0x66),
    new Command("add", [Args.D, Args.B], 0x67),
    new Command("add", [Args.A, Args.C], 0x68),
    new Command("add", [Args.B, Args.C], 0x69),
    new Command("inc", [Args.C], 0x6A),
    new Command("add", [Args.D, Args.C], 0x6B),
    new Command("add", [Args.A, Args.D], 0x6C),
    new Command("add", [Args.B, Args.D], 0x6D),
    new Command("add", [Args.C, Args.D], 0x6E),
    new Command("inc", [Args.D], 0x6F),

    new Command("dec", [Args.A], 0x70),
    new Command("sub", [Args.B, Args.A], 0x71),
    new Command("sub", [Args.C, Args.A], 0x72),
    new Command("sub", [Args.D, Args.A], 0x73),
    new Command("sub", [Args.A, Args.B], 0x74),
    new Command("dec", [Args.B], 0x75),
    new Command("sub", [Args.C, Args.B], 0x76),
    new Command("sub", [Args.D, Args.B], 0x77),
    new Command("sub", [Args.A, Args.C], 0x78),
    new Command("sub", [Args.B, Args.C], 0x79),
    new Command("dec", [Args.C], 0x7A),
    new Command("sub", [Args.D, Args.C], 0x7B),
    new Command("sub", [Args.A, Args.D], 0x7C),
    new Command("sub", [Args.B, Args.D], 0x7D),
    new Command("sub", [Args.C, Args.D], 0x7E),
    new Command("dec", [Args.D], 0x7F),

    new Command("not", [Args.A], 0x80),
    new Command("adc", [Args.B, Args.A], 0x81),
    new Command("adc", [Args.C, Args.A], 0x82),
    new Command("adc", [Args.D, Args.A], 0x83),
    new Command("adc", [Args.A, Args.B], 0x84),
    new Command("not", [Args.B], 0x85),
    new Command("adc", [Args.C, Args.B], 0x86),
    new Command("adc", [Args.D, Args.B], 0x87),
    new Command("adc", [Args.A, Args.C], 0x88),
    new Command("adc", [Args.B, Args.C], 0x89),
    new Command("not", [Args.C], 0x8A),
    new Command("adc", [Args.D, Args.C], 0x8B),
    new Command("adc", [Args.A, Args.D], 0x8C),
    new Command("adc", [Args.B, Args.D], 0x8D),
    new Command("adc", [Args.C, Args.D], 0x8E),
    new Command("not", [Args.D], 0x8F),

    new Command("neg", [Args.A], 0x90),
    new Command("sbb", [Args.B, Args.A], 0x91),
    new Command("sbb", [Args.C, Args.A], 0x92),
    new Command("sbb", [Args.D, Args.A], 0x93),
    new Command("sbb", [Args.A, Args.B], 0x94),
    new Command("neg", [Args.B], 0x95),
    new Command("sbb", [Args.C, Args.B], 0x96),
    new Command("sbb", [Args.D, Args.B], 0x97),
    new Command("sbb", [Args.A, Args.C], 0x98),
    new Command("sbb", [Args.B, Args.C], 0x99),
    new Command("neg", [Args.C], 0x9A),
    new Command("sbb", [Args.D, Args.C], 0x9B),
    new Command("sbb", [Args.A, Args.D], 0x9C),
    new Command("sbb", [Args.B, Args.D], 0x9D),
    new Command("sbb", [Args.C, Args.D], 0x9E),
    new Command("neg", [Args.D], 0x9F),

    new Command("clr", [Args.A], 0xA0),
    new Command("mov", [Args.B, Args.A], 0xA1),
    new Command("mov", [Args.C, Args.A], 0xA2),
    new Command("mov", [Args.D, Args.A], 0xA3),
    new Command("mov", [Args.A, Args.B], 0xA4),
    new Command("clr", [Args.B], 0xA5),
    new Command("mov", [Args.C, Args.B], 0xA6),
    new Command("mov", [Args.D, Args.B], 0xA7),
    new Command("mov", [Args.A, Args.C], 0xA8),
    new Command("mov", [Args.B, Args.C], 0xA9),
    new Command("clr", [Args.C], 0xAA),
    new Command("mov", [Args.D, Args.C], 0xAB),
    new Command("mov", [Args.A, Args.D], 0xAC),
    new Command("mov", [Args.B, Args.D], 0xAD),
    new Command("mov", [Args.C, Args.D], 0xAE),
    new Command("clr", [Args.D], 0xAF),

    new Command("test", [Args.A], 0xB0),
    new Command("and", [Args.B, Args.A], 0xB1),
    new Command("and", [Args.C, Args.A], 0xB2),
    new Command("and", [Args.D, Args.A], 0xB3),
    new Command("and", [Args.A, Args.B], 0xB4),
    new Command("test", [Args.B], 0xB5),
    new Command("and", [Args.C, Args.B], 0xB6),
    new Command("and", [Args.D, Args.B], 0xB7),
    new Command("and", [Args.A, Args.C], 0xB8),
    new Command("and", [Args.B, Args.C], 0xB9),
    new Command("test", [Args.C], 0xBA),
    new Command("and", [Args.D, Args.C], 0xBB),
    new Command("and", [Args.A, Args.D], 0xBC),
    new Command("and", [Args.B, Args.D], 0xBD),
    new Command("and", [Args.C, Args.D], 0xBE),
    new Command("test", [Args.D], 0xBF),

    new Command("rcl", [Args.A], 0xC0),
    new Command("or", [Args.B, Args.A], 0xC1),
    new Command("or", [Args.C, Args.A], 0xC2),
    new Command("or", [Args.D, Args.A], 0xC3),
    new Command("or", [Args.A, Args.B], 0xC4),
    new Command("rcl", [Args.B], 0xC5),
    new Command("or", [Args.C, Args.B], 0xC6),
    new Command("or", [Args.D, Args.B], 0xC7),
    new Command("or", [Args.A, Args.C], 0xC8),
    new Command("or", [Args.B, Args.C], 0xC9),
    new Command("rcl", [Args.C], 0xCA),
    new Command("or", [Args.D, Args.C], 0xCB),
    new Command("or", [Args.A, Args.D], 0xCC),
    new Command("or", [Args.B, Args.D], 0xCD),
    new Command("or", [Args.C, Args.D], 0xCE),
    new Command("rcl", [Args.D], 0xCF),

    new Command("rcr", [Args.A], 0xD0),
    new Command("xor", [Args.B, Args.A], 0xD1),
    new Command("xor", [Args.C, Args.A], 0xD2),
    new Command("xor", [Args.D, Args.A], 0xD3),
    new Command("xor", [Args.A, Args.B], 0xD4),
    new Command("rcr", [Args.B], 0xD5),
    new Command("xor", [Args.C, Args.B], 0xD6),
    new Command("xor", [Args.D, Args.B], 0xD7),
    new Command("xor", [Args.A, Args.C], 0xD8),
    new Command("xor", [Args.B, Args.C], 0xD9),
    new Command("rcr", [Args.C], 0xDA),
    new Command("xor", [Args.D, Args.C], 0xDB),
    new Command("xor", [Args.A, Args.D], 0xDC),
    new Command("xor", [Args.B, Args.D], 0xDD),
    new Command("xor", [Args.C, Args.D], 0xDE),
    new Command("rcr", [Args.D], 0xDF),

    new Command("shl", [Args.A], 0xE0),
    new Command("shl", [Args.B], 0xE1),
    new Command("shl", [Args.C], 0xE2),
    new Command("shl", [Args.D], 0xE3),
    new Command("shr", [Args.A], 0xE4),
    new Command("shr", [Args.B], 0xE5),
    new Command("shr", [Args.C], 0xE6),
    new Command("shr", [Args.D], 0xE7),
    new Command("sar", [Args.A], 0xE8),
    new Command("sar", [Args.B], 0xE9),
    new Command("sar", [Args.C], 0xEA),
    new Command("sar", [Args.D], 0xEB),
    new Command("rnd", [Args.A], 0xEC),
    new Command("rnd", [Args.B], 0xED),
    new Command("rnd", [Args.C], 0xEE),
    new Command("rnd", [Args.D], 0xEF),
];
